//====================================================================================================
// Base code generated with Relativity: HTTP Service Controller Gen (Build 3.0.5701.25371)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by vcontreras at DINFTEC-P1-5 on 08/21/2019 12:55:17 
//====================================================================================================

using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Safari.Entities;


namespace Safari.Services.Contracts
{
    [DataContract]
    public partial class AgregarEspecieResponse
    {
        [DataMember]
        public Especie Result { get; set; }
    }
}

